# Generated by Django 4.1.7 on 2023-11-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id_user", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=200)),
                ("senha", models.CharField(max_length=200)),
                ("estagio", models.CharField(max_length=200)),
                ("perfil_photo", models.ImageField(max_length=500, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id_question", models.BigAutoField(primary_key=True, serialize=False)),
                ("data_envio", models.DateTimeField(verbose_name="data do envio")),
                ("acessos", models.IntegerField(default=0)),
                ("tag", models.TextField(max_length=200)),
                ("pergunta", models.TextField(max_length=500)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_app.users",
                    ),
                ),
            ],
        ),
    ]
