# Generated by Django 4.1.7 on 2023-11-03 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions", old_name="question", new_name="id_question",
        ),
    ]
