# Generated by Django 4.1.7 on 2023-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="estagio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="numero",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="senha",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
