# Generated by Django 4.2.7 on 2023-11-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_question_questions_id_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='estagio',
            field=models.IntegerField(verbose_name='Ano escolar'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='users',
            name='numero',
            field=models.IntegerField(verbose_name='Número CMSM'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Senha'),
        ),
    ]
