# Generated by Django 4.1.7 on 2023-12-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_alter_users_email_alter_users_estagio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="disciplinas",
            fields=[
                ("id_disci", models.BigAutoField(primary_key=True, serialize=False)),
                ("nivel", models.IntegerField(default=0)),
                ("ano", models.IntegerField(default=0)),
                ("nome", models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="username"),
        ),
        migrations.CreateModel(
            name="respostas",
            fields=[
                ("id_resp", models.BigAutoField(primary_key=True, serialize=False)),
                ("data_envio", models.DateTimeField(verbose_name="data do envio")),
                ("acessos", models.IntegerField(default=0)),
                ("tag", models.TextField(max_length=200)),
                ("resposta", models.TextField(max_length=500)),
                (
                    "aprovada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autor_aprovacao",
                        to="django_app.users",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autor_resposta",
                        to="django_app.users",
                    ),
                ),
            ],
        ),
    ]
