# Generated by Django 4.2.7 on 2023-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_users_estagio_alter_users_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
